base_image: "registry.access.redhat.com/ubi9/ubi-minimal:latest"
version: "2.6.10"
description: "OpenLDAP - Open Source LDAP Directory Server (LTS Release)"

# Default platforms (can be overridden with --platform flag)
platforms: "linux/amd64,linux/arm64"

build_args:
  OPENLDAP_VERSION: "2.6.10"
