services:
  openldap:
    image: zonlykroks/openldap:latest
    container_name: openldap-secure

    user: "1000:1000"
    read_only: true

    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true

    ports:
      - "389:389"
      - "636:636"

    environment:
      LDAP_DATA_DIR: /var/lib/ldap
      LDAP_CONFIG_DIR: /usr/local/openldap/etc/openldap/slapd.d

    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/usr/local/openldap/etc/openldap/slapd.d
      - type: tmpfs
        target: /var/run/openldap
        tmpfs:
          size: 10M
          mode: 1777

    healthcheck:
      test: ["/usr/local/openldap/libexec/slapd", "-VV"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  ldap-data:
    driver: local
  ldap-config:
    driver: local
