name: Check for Version Updates

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for updates
        id: check
        run: |
          if [ -f check-version.sh ]; then
            chmod +x check-version.sh
            ./check-version.sh
          else
            echo "No check-version.sh found"
            exit 1
          fi

      - name: Create Pull Request
        if: steps.check.outputs.update_available == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update to ${{ steps.check.outputs.new_version }}"
          title: "chore: update to ${{ steps.check.outputs.new_version }}"
          body: |
            ## Update MinIO image

            **Current version:** `${{ steps.check.outputs.current_version }}`
            **New version:** `${{ steps.check.outputs.new_version }}`

            This PR was automatically generated by the version check workflow.

            ### Release Notes
            ${{ steps.check.outputs.release_notes }}
          branch: update/minio-${{ steps.check.outputs.new_version }}
          labels: |
            dependencies
            minio
          delete-branch: true